### ISSUE TITLE
libfranka for Linux arm64

### ISSUE THREAD

**Issue by mlaves** [RoboStack/ros-noetic#108]
I just came across this awesome project. However for my work, `ros-noetic-libfranka` for linux on arm64 is still missing. I tried to create a custom package using `vinca` but was unable to do so. Could you create this package or hint me on how to create it myself?

**Comment by mlaves** [comment]
Done! Thanks for the very quick response

**Comment by wolfv** [comment]
here is the build: https://dev.azure.com/roboforge/ros_pipelines/_build/results?buildId=1841&view=logs&j=1af1dc03-1af3-5fb1-94be-7682c40b8e14

(kicked off from the `buildbranch_linux_aarch64` in this repo :)

**Comment by wolfv** [comment]
Package is uploaded to the robostack channel https://anaconda.org/RoboStack/ros-noetic-libfranka/files

Let us know how it goes :)
