### ISSUE TITLE
it is fool to must link opencv 4.2 on ros

### ISSUE THREAD

**Issue by graphic-zhang** [RoboStack/ros-noetic#127]
it will cause confict when developer use different opencv version or different modules

**Comment by wolfv** [comment]
Hi @graphic-zhang I think we're using opencv 4.5 currently. What version are you interested in? We need to decide on some version at some point, otherwise we need to constantly update the code etc.

**Comment by Tobias-Fischer** [comment]
Indeed, we're using opencv 4.5: https://github.com/RoboStack/ros-noetic/blob/cca5378e0a0c09974119e39964cf14a7143baccf/additional_recipes/ros-distro-mutex/recipe.yaml#L36

And also agreed that we need to pick a certain version; we can't possibly build against all different versions of opencv that are out there.

**Comment by wolfv** [comment]
@graphic-zhang do you have a specific use-case where you ran into issues?

**Comment by graphic-zhang** [comment]
> Hi @graphic-zhang I think we're using opencv 4.5 currently. What version are you interested in? We need to decide on some version at some point, otherwise we need to constantly update the code etc.

first , I apologize for my talk way，and i install ros by  ros-wiki website . 
 I have to point a situation ： even  I set OpenDIR or anyother ways to  set cmake  find and link myself opencv_lib (3.4.10 which has  i have built ) ,   cv_bridge will always link ros opencv lib 4.x.x ,  and then program will dead in opencv function which i have never encountered.
At last , i have to set Opencv_DIR to ros opencv in /usr/x86_64*/cmake/opencv4 , it worked , but it's too  Exclusive, i have to use ros opencv if i wanna use ros cv_bridge . is there any other way to make them more Compatible?

**Comment by wolfv** [comment]
Hi, mixing the ROS installation from ROS wiki and the conda installation will not work. 

We have a version of `ros-noetic-cv-bridge` that should use a compatible OpenCV version (4.5).

Can you try wiht `conda install ros-noetic-cv-bridge` again?

**Comment by graphic-zhang** [comment]
> Hi, mixing the ROS installation from ROS wiki and the conda installation will not work.
> 
> We have a version of `ros-noetic-cv-bridge` that should use a compatible OpenCV version (4.5).
> 
> Can you try wiht `conda install ros-noetic-cv-bridge` again?

I am very confused , maybe I should try more.

**Comment by Tobias-Fischer** [comment]
We may be able to help if you provide us with a detailed report on what you are trying to achieve, which exact commands you use, the output of `conda list`, whether you follow the instructions in the readme precisely, etc.
