### ISSUE TITLE
Problem installing ROS OS on Ubuntu (apt update fails)

### ISSUE THREAD

**Issue by seyedrezabazyar** [RoboStack/ros-noetic#150]
Hello. I encountered this error while installing ROS

W: GPG error: http://packages.ros.org/ros2/ubuntu focal InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY F42ED6FBAB17C54

`https://ibb.co/Zcv09p4`

**Comment by Tobias-Fischer** [comment]
Hi, this repository is for the conda installation of ROS, see the readme. If you want to use the standard apt way, please ask your questions on https://answers.ros.org/questions/
