### ISSUE TITLE
Build DepthAI ROS

### ISSUE THREAD

**Issue by Tobias-Fischer** [RoboStack/ros-noetic#151]
https://github.com/rapyuta-robotics/depthai_ros/

**Comment by Tobias-Fischer** [comment]
Hi @ kunaltyagi - is there any chance to create a release of DepthAI ROS? In this case building it here should be reasonably easy, without a release it's quite hard ..

**Comment by Tobias-Fischer** [comment]
Kind ping @kunaltyagi

**Comment by kunaltyagi** [comment]
Yeah. We're working on a stable version. There have been a few changes in the API on our end, and we need to get those out

**Comment by Tobias-Fischer** [comment]
No stable version - closing.
