### ISSUE TITLE
error retrieving package ros-noetic-smach-ros-2.5.0-py38he9ab703_6.tar.bz2

### ISSUE THREAD

**Issue by tadteo** [RoboStack/ros-noetic#162]
Hi,

I am trying to install ros-noetic-desktop-full using the command:
```
conda create -n ros ros-noetic-desktop-full -c conda-forge -c robostack && conda activate ros
```
but every time I try I got the error 500.

```
Downloading and Extracting Packages
ros-noetic-smach-ros | 32 KB     |                                                                                                                                                                          |   0% 

CondaHTTPError: HTTP 500 INTERNAL SERVER ERROR for url <https://conda.anaconda.org/robostack/linux-64/ros-noetic-smach-ros-2.5.0-py38he9ab703_6.tar.bz2>
Elapsed: 00:07.973270
CF-RAY: 68eb4b792dd8f152-ARN
```

I have tried to manually download other versions of that package and it is not a problem but with that specific version, I continually get Internal Server Error 500.

What can I do to solve the problem?

**Comment by Tobias-Fischer** [comment]
Hi @tadteo - that's a weird one. I can download the file without issues. What happens if you try `wget https://conda.anaconda.org/robostack/linux-64/ros-noetic-smach-ros-2.5.0-py38he9ab703_6.tar.bz2`? Does that work?

**Comment by tadteo** [comment]
Hi @Tobias-Fischer,
Thank you for the fast reply!
 
When I tried downloading that specific packet 2 hours ago was not working. I have just retried now and the installation worked without a problem.
Probably a temporary server error.
 
Thank you again for your time and wonderful project!
