### ISSUE TITLE
Turtlebot3 Autorace Windows -errors when building

### ISSUE THREAD

**Issue by robogeekcanada** [RoboStack/ros-noetic#169]
I am trying to build turtlebot3_autorace package using `rosdep` in Windows.

These are the steps I followed so far, and the error I am encountering. Please let me know I am going in the right direction:

$ conda activate t3_autorace_env
$ conda install -c conda-forge mamba

$ mkdir catkin_ws
$ cd catkin_ws
$ mkdir src 
$ git clone https://github.com/ROBOTIS-GIT/turtlebot3_autorace_2020.git
$ cd ..
$ rosdep update
$ rosdep install --from-paths src --ignore-src -r -y

Missing dependencies, fix them first..
$ conda install -c prometeia enum34

This works but the following errors come up: 

![RoboStack T3 Autorace](https://user-images.githubusercontent.com/32141561/134005084-dda45f9b-99bc-45df-9520-b088728414ac.PNG)

Seems `ros-noetic-image-geometry` is looking for specifically version 4.5.1 < 4.5.2.a0 for `libopencv`

**Comment by Tobias-Fischer** [comment]
This is another case where a rebuild of packages is required ..

/Cc @wolfv
