### ISSUE TITLE
Global rebuild issue?

### ISSUE THREAD

**Issue by baszalmstra** [RoboStack/ros-noetic#179]
Im trying to create an environment which contains: `ros-noetic-message-generation` and `ros-noetic-pcl-ros`. However Im running into issues because `ros-noetic-message-generation` is constrained by `ros-distro-mutex 0.2.*` but there is no version of `ros-noetic-pcl-ros` yet that has the same constrained (only versions constrained by `ros-distro mutex 0.1.*`. This causes the solver to fall back to `ros-noetic-pcl-ros 1.7.2 build 3` (7 months old) which contains a bug.

It looks like during the global rebuild introduced with #170 not all packages where build which causes this issue. This is quite problematic since now we get a few incompatible packages. 

For now I simply lock the `ros-distro-mutex` to `0.1.0` in my environment, however I would love an update when I can remove this workaround!

**Comment by Tobias-Fischer** [comment]
Hi @baszalmstra, yes you are correct, at the moment not all packages are rebuilt yet. Locking the `ros-distro-mutex` to `0.1.0` is the way to go at this time.

Let us know if you are interested in contributing - additional people would help accelerating our progress :)

**Comment by baszalmstra** [comment]
I now simply build my packages with a dependency on `ros-distro-mutex`. This solved the issue for me.
