### ISSUE TITLE
sudo: apt-get: command not found

### ISSUE THREAD

**Issue by vikramadityafcb** [RoboStack/ros-noetic#189]
Newbie trying to learn ROS. Tried running `$ sudo apt-get install ros-noetic-ros-tutorials` from [http://wiki.ros.org/ROS/Tutorials/NavigatingTheFilesystem](http://wiki.ros.org/ROS/Tutorials/NavigatingTheFilesystem) but it resulted in the following error: 

sudo: apt-get: command not found

Screenshots attached below for your reference.

Thank you so much for helping out!!

<img width="836" alt="Screenshot 2021-11-14 at 4 10 04 PM" src="https://user-images.githubusercontent.com/59144331/141698725-42ba4907-3b16-447c-927d-d6c8df754ab5.png">
![Screenshot 2021-11-14 at 3 58 36 PM](https://user-images.githubusercontent.com/59144331/141698726-77f59379-6cc2-45da-960b-e7817e3bc391.png)

**Comment by wolfv** [comment]
Apt get is the package manager on Ubuntu. Since you are using macOS and robostack you should use mamba or conda. The command should otherwise look the same:

Mamba install ros-noetic-ros-tutorials

**Comment by vikramadityafcb** [comment]
Thank you so much! Was stuck on this for a long time 😅. I really really appreciate that you took out time to answer such a simple question!
