### ISSUE TITLE
Turtlesim graphics not showing up

### ISSUE THREAD

**Issue by vikramadityafcb** [RoboStack/ros-noetic#192]
When I try to run `rosrun turtlesim turtlesim_node` I get the following output 

> [ INFO] [1637036965.024629000]: Starting turtlesim with node name /turtlesim
[ INFO] [1637036965.029622000]: Spawning turtle [turtle1] at x=[5.544445], y=[5.544445], theta=[0.000000]

However, while it initiates a turtlesim_node.exec, I cannot see the turtle and the other graphics as shown in this [http://wiki.ros.org/ROS/Tutorials/UnderstandingTopics](http://wiki.ros.org/ROS/Tutorials/UnderstandingTopics).

How can I solve this? 

Thank you so much for your help!!

**Comment by Tobias-Fischer** [comment]
Hi @vikramadityafcb, is this on osx? If so, let's please stick to https://github.com/RoboStack/ros-noetic/issues/158

If it's on another platform, please let us know here.

**Comment by vikramadityafcb** [comment]
It's on OSX. My bad, I did not see the previous thread. 
Thank you for the quick response!
