### ISSUE TITLE
 Turtlebot3 use problem in minconda

### ISSUE THREAD

**Issue by nfhe** [RoboStack/ros-noetic#203]
I created a neotic version of ros in the linux version and minconda following the tutorial. I want to use the gazebo simulation of turtlebot3. When I run roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch, it runs without errors and cannot run the lidar plugin, but the lidar can be displayed. There is no scan node . I have searched for several days and have not found the problem. I am wondering if it is a problem with my installation, or which version is wrong.
![image](https://user-images.githubusercontent.com/92715669/145136444-75f4913b-0de8-441e-853a-694402e667ee.png)
![image](https://user-images.githubusercontent.com/92715669/145136482-76ba2248-dd44-46ee-8ca0-64539695d894.png)

I look forward to reply from you.Thank you.

**Comment by traversaro** [comment]
Hi @nfhe!

> When I run roslaunch turtlebot3_gazebo turtlebot3_empty_world.launch, it runs without errors and cannot run the lidar plugin, but the lidar can be displayed. 

If you are following a tutorial that explain this aspects, can you link it? Thanks!

>  There is no scan node 

Which scan node do you expect should be running? How are you checking if it is running? Thanks!
