### ISSUE TITLE
While trying to install ros noetic error

### ISSUE THREAD

**Issue by Allenkurian** [RoboStack/ros-noetic#209]
Solving environment: failed with initial frozen solve. Retrying with flexible solve

**Comment by wolfv** [comment]
Please add more context

**Comment by Allenkurian** [comment]
<img width="568" alt="Screenshot 2022-01-20 at 5 58 43 PM" src="https://user-images.githubusercontent.com/65230534/150338782-c28ce6af-5607-47ea-a8a5-dc1215e6c7dc.png">

**Comment by Tobias-Fischer** [comment]
Please use mamba instead of conda. Feel free to reopen if it does not work with mamba.
