### ISSUE TITLE
Command prompt not working 

### ISSUE THREAD

**Issue by SoumyajitProjects** [RoboStack/ros-noetic#214]
I have entering all the prompts onto my terminal on mac, I entered the **mamba install ros-noetic-desktop** prompt but it displays:

Encountered problems while solving:
 - nothing provides requested ros-noetic 
 - nothing provides requested desktop

How would I fix this issue?

**Comment by wolfv** [comment]
@SoumyajitProjects it looks like you have a space between `ros-noetic` and `desktop`. Please try again with

`mamba install ros-noetic-desktop`
