### ISSUE TITLE
Scene and environment renders on gazebo but the robot arm doesn't

### ISSUE THREAD

**Issue by tohsin** [RoboStack/ros-noetic#220]
I am trying to run the simple arm package from the udacity ros course.
`https://github.com/udacity/simple_arm_01.git simple_arm`
The scene shows up but the  robot arm won't render in gazebo.
i get this warning at the end, not sure if thats the problem but i have checked how to fix it and the solutions didnt work
`Controller Spawner couldn't find the expected controller_manager ROS interface`
I use a mac

**Comment by wolfv** [comment]
You may miss the `ros-noetic-gazebo-ros-control` package?  

https://answers.ros.org/question/256820/warn-controller-spawner-couldnt-find-the-expected-controller_manager-ros-interface/

**Comment by tohsin** [comment]
Yeah i tried that with `mamba install ros-noetic-gazebo-ros-control` the arm  still wont render and the warning is still there

**Comment by Tobias-Fischer** [comment]
Is that still an issue @tohsin? Which platform are you on?

**Comment by Tobias-Fischer** [comment]
Closing here as we don't have sufficient information. Feel free to reopen @tohsin
