### ISSUE TITLE
Missing icons on rqt applications

### ISSUE THREAD

**Issue by agtbaskara** [RoboStack/ros-noetic#225]
I notice that when running rqt apps, like rqt_bag most of the icons are missing.

I am running a fresh installation of Ubuntu 20.04

Here is a screenshot of rqt_bag with missing icons:

![rqt_bag before](https://user-images.githubusercontent.com/15165276/153150706-b6da9d51-4a46-45f3-95c1-a9a7ab2a02a7.png)

For now, the temporary solution for me is to install `tango-icon-theme` on the system manually using `sudo apt install tango-icon-theme`

I reference this for the temporary solution [https://answers.ros.org/question/372890/rqt-button-not-show-icon/](url)

Here is a screenshot of rqt_bag after installing `tango-icon-theme` : 

![rqt_bag after](https://user-images.githubusercontent.com/15165276/153152876-a6920d22-a7d1-4433-9de5-bfce57f48ac0.png)

Notice that there is still some icons are still missing like the thumbnail icon

**Comment by Tobias-Fischer** [comment]
Can you try mamba install -c conda-forge adwaita-icon-theme?

**Comment by agtbaskara** [comment]
I have tried that before finding the `tango-icon-theme` solution, and It doesn't help in my case.

Probably we need to create a new conda package for `tango-icon-theme` or set some system variable in the conda ros env, so it uses `adwaita-icon-theme` as default?

**Comment by Tobias-Fischer** [comment]
How about `conda install -c robostack-experimental ros-galactic-tango-icons-vendor`?

**Comment by agtbaskara** [comment]
I have tested it, and it doesn't work (I uninstall the tango-icon-theme from the system and reboot the system before testing)

**Comment by wolfv** [comment]
weird, in your second screenshot icons that existed in teh first screenshot have gone missing.

**Comment by agtbaskara** [comment]
Probably because `tango-icon-theme` itself is incomplete

**Comment by agtbaskara** [comment]
Interestingly I tried to install `gnome-icon-theme` by using `sudo apt install gnome-icon-theme` and all the icons are now appears

Here is a screenshot of rqt_bag after installing `gnome-icon-theme` :
![rqt_bag gnome](https://user-images.githubusercontent.com/15165276/153176962-c78e0b14-aa0c-4be7-af73-b8b65fd00873.png)

**Comment by wolfv** [comment]
Great! This is really good to know.
We need to figure out if `adwaita-icon-theme` on conda-forge covers the same icons or what's missing.

**Comment by agtbaskara** [comment]
I already tried to install `adwaita-icon-theme` from conda-forge before (`mamba install -c conda-forge adwaita-icon-theme`)
But the icons are still missing (same as my first screenshot)

Probably this is because rqt use `gnome-icon-theme` rather than `adwaita-icon-theme` as default icon

**Comment by Tobias-Fischer** [comment]
This also happens on other platforms unfortunately - and there's no way workaround on osx

**Comment by Tobias-Fischer** [comment]
Xref https://github.com/conda-forge/qt-main-feedstock/issues/120
@hmaarrfk has done some great work for better system integration of qt, I wonder if this will help here?

**Comment by hmaarrfk** [comment]
i'm not so sure. I haven't really hit any of these issues myself. sometimes starting things from the terminal really helps.

**Comment by Tobias-Fischer** [comment]
Do you know if this is an issue on windows as well @traversaro?

**Comment by Tobias-Fischer** [comment]
I’m trying to build the old gnome icon theme to see if this fixes the issue: https://github.com/conda-forge/staged-recipes/pull/22077

**Comment by Tobias-Fischer** [comment]
Alright .. after going through all the trouble in building gnome-icon-theme, I found that this does not fix the issue after all. However, it sent me off the right path. Basically, QIcon isn't looking in the right directories by default. I patched python-qt-binding to look into the conda_prefix: https://github.com/RoboStack/ros-noetic/commit/e94f566d4972dd128fb684856df837c4e4edf4b8

Then all that is needed is installing the proper theme, which I enforce in https://github.com/RoboStack/ros-noetic/commit/3b40e3df393011378720d73c601de0bb4070d3aa (thankfully the themes are available for all platforms).

This fixes the issue locally on my MacOS machine. Could you please try it on your Linux machine @agtbaskara? You might need to recreate the env, I've overwritten the ros-noetic-python-qt-binding package with a new one that contains the patch.

Closing here, feel free to reopen.

**Comment by hmaarrfk** [comment]
ah good find!

**Comment by Flova** [comment]
I noticed that you might need adwaita-icon-theme = "<40"  as non-symbolic icons that are used by e.g. rqt have been removed in newer versions-

**Comment by traversaro** [comment]
> I noticed that you might need adwaita-icon-theme = "<40" as non-symbolic icons that are used by e.g. rqt have been removed in newer versions-

Interestingly, can you explain more on this? We can probably add the `adwaita-icon-theme` bound to affected packages. I guess there is nothing meanginful we can do to fix the issue in https://github.com/conda-forge/adwaita-icon-theme-feedstock ?

**Comment by Flova** [comment]
Most icons have a colorful/skeuomorphic default version and a more flat "symbolic" version. This is indicated by the "-symbolic" name suffix. It seems like that for newer versions adwaita dropped the skeuomorphic ones used by e.g. rqt. I think this is an opinionated design choice. Either we can migrate rqt and it's plugins to use the modern ones or we can add a version constraint to adwaita.

**Comment by traversaro** [comment]
Interesting, depending on which version of `adwaita-icon-theme` version did this change, I guess this problem may also affect ROS-O people (https://github.com/ros-o), we may check if they have some useful patch.

**Comment by Flova** [comment]
I don't remember if 40 was the exact one, but it should be close.
