### ISSUE TITLE
rosdep can't find mamba

### ISSUE THREAD

**Issue by vanem** [RoboStack/ros-noetic#260]
On a fresh robostack Windows install, I am able to run mamba directly from the environment, but if I run rosdep on a workspace:
`rosdep install --from-paths src --ignore-src -r -y --rosdistro noetic`
I get:
`Bad installer [conda]: None of micromamba.exe, mamba.exe, conda.exe was found.`

**Comment by traversaro** [comment]
Hi @vanem, what do you mean by "if I run rosdep on a workspace"? Even if you are using a catkin workspace, you should always activate the corresponding conda/mamba environment.

**Comment by vanem** [comment]
Hi @traversaro. The robostack environment is indeed activated (otherwise the rosdep command would not be found at all). I'm also able to run catkin_make for example and build C++ packages. Here is the complete result of running rosdep:

```
(robostackenv) C:\_work\prj\ros1\ws>rosdep install --from-paths src --ignore-src -r -y

ERROR: Rosdep experienced an internal error.
Please go to the rosdep page [1] and file a bug report with the message below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.21.0

Bad installer [conda]: None of micromamba.exe, mamba.exe, conda.exe was found.
```

**Comment by traversaro** [comment]
Can you list the content of your environment with `mamba list` ? Thanks!

**Comment by vanem** [comment]
# packages in environment at c:\_work\app\miniforge3\envs\robostackenv:
#
# Name                    Version                   Build  Channel
apr                       1.7.0                he38c35c_5    conda-forge
assimp                    5.2.3                hc2aa0de_1    conda-forge
bcrypt                    3.2.2            py39hb82d6ee_0    conda-forge
boost                     1.74.0           py39hefe7e4c_5    conda-forge
boost-cpp                 1.74.0               h9f4b32c_8    conda-forge
brotli                    1.0.9                h8ffe710_7    conda-forge
brotli-bin                1.0.9                h8ffe710_7    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
c-compiler                1.4.2                h8ffe710_0    conda-forge
ca-certificates           2022.4.26            haa95532_0    anaconda
cairo                     1.16.0            h15b3021_1010    conda-forge
catkin_pkg                0.4.24             pyhd8ed1ab_1    conda-forge
certifi                   2021.10.8        py39hcbf5309_2    conda-forge
cffi                      1.15.0           py39h0878f49_0    conda-forge
clangdev                  5.0.0                   flang_3    conda-forge
cmake                     3.23.1               h39d44d4_0    conda-forge
colorama                  0.4.4              pyhd3eb1b0_0    anaconda
compilers                 1.4.2                h57928b3_0    conda-forge
console_bridge            1.0.2                h5362a0b_1    conda-forge
cryptography              36.0.2           py39h7bc7c5c_1    conda-forge
curl                      7.83.0               h789b8ee_0    conda-forge
cxx-compiler              1.4.2                h2d74725_0    conda-forge
cycler                    0.11.0             pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distro                    1.6.0              pyhd8ed1ab_0    conda-forge
docutils                  0.18.1           py39hcbf5309_1    conda-forge
double-conversion         3.2.0                h0e60522_0    conda-forge
eigen                     3.4.0                h2d74725_0    conda-forge
empy                      3.3.4              pyh9f0ad1d_1    conda-forge
expat                     2.4.8                h39d44d4_0    conda-forge
ffmpeg                    4.3.1                ha925a31_0    conda-forge
flang                     5.0.0           he025d50_20180525    conda-forge
flang_win-64              5.0.0           h13ae965_20180526    conda-forge
flann                     1.9.1             h075982a_1010    conda-forge
font-ttf-dejavu-sans-mono 2.37                 hab24e00_0    conda-forge
font-ttf-inconsolata      3.000                h77eed37_0    conda-forge
font-ttf-source-code-pro  2.038                h77eed37_0    conda-forge
font-ttf-ubuntu           0.83                 hab24e00_0    conda-forge
fontconfig                2.14.0               hce3cb01_0    conda-forge
fonts-conda-ecosystem     1                             0    conda-forge
fonts-conda-forge         1                             0    conda-forge
fonttools                 4.33.3           py39hb82d6ee_0    conda-forge
fortran-compiler          1.4.2                h9655429_0    conda-forge
freeglut                  3.2.2                h0e60522_1    conda-forge
freeimage                 3.18.0               h6676e37_8    conda-forge
freetype                  2.10.4               h546665d_1    conda-forge
fribidi                   1.0.10               h8d14728_0    conda-forge
getopt-win32              0.1                  h8ffe710_0    conda-forge
gettext                   0.19.8.1          ha2e2712_1008    conda-forge
gl2ps                     1.4.2                hce2df77_1    anaconda
glew                      2.1.0                hd77b12b_3    anaconda
gmock                     1.11.0               h2d74725_0    conda-forge
graphite2                 1.3.13                     1000    conda-forge
graphviz                  2.50.0               had6c3a3_2    conda-forge
gtest                     1.11.0               h2d74725_0    conda-forge
gts                       0.7.6                h7c369d9_2    conda-forge
harfbuzz                  4.2.0                hc1763ed_0    conda-forge
hdf4                      4.2.15               h0e5069d_3    conda-forge
hdf5                      1.12.1          nompi_h2a0e4a3_104    conda-forge
icu                       69.1                 h0e60522_0    conda-forge
imath                     3.1.5                h12d4b20_0    conda-forge
intel-openmp              2022.0.0          h57928b3_3663    conda-forge
jasper                    2.0.33               h77af90b_0    conda-forge
jbig                      2.1               h8d14728_2003    conda-forge
jpeg                      9e                   h8ffe710_1    conda-forge
jsoncpp                   1.9.5                h2d74725_1    conda-forge
jxrlib                    1.1                  h8ffe710_2    conda-forge
kiwisolver                1.4.2            py39h2e07f2f_1    conda-forge
krb5                      1.19.3               h1176d77_0    conda-forge
lcms2                     2.12                 h2a16943_0    conda-forge
lerc                      3.0                  h0e60522_0    conda-forge
libapr                    1.7.0                h8ffe710_5    conda-forge
libapriconv               1.2.2                h8ffe710_5    conda-forge
libaprutil                1.6.1                h311b4f7_5    conda-forge
libblas                   3.9.0              14_win64_mkl    conda-forge
libbrotlicommon           1.0.9                h8ffe710_7    conda-forge
libbrotlidec              1.0.9                h8ffe710_7    conda-forge
libbrotlienc              1.0.9                h8ffe710_7    conda-forge
libcblas                  3.9.0              14_win64_mkl    conda-forge
libclang                  13.0.1          default_h81446c8_0    conda-forge
libcurl                   7.83.0               h789b8ee_0    conda-forge
libdeflate                1.10                 h8ffe710_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libflang                  5.0.0           h6538335_20180525    conda-forge
libgd                     2.3.3                h217ff3b_2    conda-forge
libglib                   2.70.2               h3be07f2_4    conda-forge
libiconv                  1.16                 he774522_0    conda-forge
liblapack                 3.9.0              14_win64_mkl    conda-forge
liblapacke                3.9.0              14_win64_mkl    conda-forge
libnetcdf                 4.8.1           nompi_h1cc8e9d_102    conda-forge
libogg                    1.3.5                h2bbff1b_1    anaconda
libopencv                 4.5.5            py39hb20b4e8_9    conda-forge
libpng                    1.6.37               h1d00b33_2    conda-forge
libprotobuf               3.20.1               h7755175_0    conda-forge
libraw                    0.20.2               hee1bdec_1    conda-forge
libssh2                   1.10.0               h680486a_2    conda-forge
libtheora                 1.1.1                h8cc25b3_3    anaconda
libtiff                   4.3.0                hc4061b1_3    conda-forge
libwebp                   1.2.2                h57928b3_0    conda-forge
libwebp-base              1.2.2                h8ffe710_1    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.9.12               h0ad7f3c_0    anaconda
libzip                    1.8.0                hfed4ece_1    conda-forge
libzlib                   1.2.11            h8ffe710_1014    conda-forge
llvm-meta                 5.0.0                         0    conda-forge
log4cxx                   0.11.0               hf7dfa5a_3    conda-forge
loguru                    0.5.3            py39haa95532_3    anaconda
lz4                       4.0.0            py39h0878066_1    conda-forge
lz4-c                     1.9.3                h8ffe710_1    conda-forge
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
make                      4.3                  h3d2af85_1    conda-forge
matplotlib-base           3.5.2            py39h581301d_0    conda-forge
mkl                       2022.0.0           h0e2418a_796    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
netifaces                 0.10.9          py39hb82d6ee_1005    conda-forge
ninja                     1.10.2               haa95532_5    anaconda
ninja-base                1.10.2               h6d14046_5    anaconda
nose                      1.3.7                   py_1006    conda-forge
numpy                     1.22.3           py39h0948cea_2    conda-forge
ogre                      1.10.12              hab73eff_8    conda-forge
openexr                   3.1.5                hab3b255_0    conda-forge
openjpeg                  2.4.0                hb211442_1    conda-forge
openmp                    5.0.0                    vc14_1    conda-forge
openssl                   1.1.1o               h8ffe710_0    conda-forge
orocos-kdl                1.5.1                h415ef7b_2    conda-forge
packaging                 21.3               pyhd8ed1ab_0    conda-forge
pango                     1.50.7               h66df5b2_0    conda-forge
paramiko                  2.10.4             pyhd8ed1ab_0    conda-forge
pcl                       1.12.0               h8e4b9db_2    conda-forge
pcre                      8.45                 h0e60522_0    conda-forge
pillow                    9.1.0            py39ha53f419_2    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h8ffe710_0    conda-forge
pkg-config                0.29.2            h2bf4dc2_1008    conda-forge
poco                      1.11.1               h1176d77_0    conda-forge
proj                      9.0.0                h1cfcee9_1    conda-forge
psutil                    5.9.0            py39hb82d6ee_1    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pugixml                   1.11.4               h0e60522_0    conda-forge
py-opencv                 4.5.5            py39h832f523_9    conda-forge
pybind11                  2.9.2            py39h2e07f2f_1    conda-forge
pybind11-global           2.9.2            py39h2e07f2f_1    conda-forge
pycairo                   1.21.0           py39h1f09dad_1    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pycryptodome              3.14.1           py39hb82d6ee_1    conda-forge
pycryptodomex             3.14.1           py39hb82d6ee_1    conda-forge
pydot                     1.4.2            py39hcbf5309_1    conda-forge
pynacl                    1.5.0            py39hb3671d1_1    conda-forge
pyopengl                  3.1.6              pyh6c4a22f_0    conda-forge
pyparsing                 3.0.8              pyhd8ed1ab_0    conda-forge
pyqt                      5.12.3           py39hcbf5309_8    conda-forge
pyqt-impl                 5.12.3           py39h415ef7b_8    conda-forge
pyqt5-sip                 4.19.18          py39h415ef7b_8    conda-forge
pyqtchart                 5.12             py39h415ef7b_8    conda-forge
pyqtwebengine             5.12.1           py39h415ef7b_8    conda-forge
python                    3.9.12          h9a09f29_1_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-gnupg              0.4.8              pyhd8ed1ab_0    conda-forge
python-orocos-kdl         1.5.1            py39h415ef7b_2    conda-forge
python_abi                3.9                      2_cp39    conda-forge
pyyaml                    6.0              py39hb82d6ee_4    conda-forge
qhull                     2020.2               h70d2c02_2    conda-forge
qt                        5.12.9               h556501e_6    conda-forge
ros-distro-mutex          0.3.0                    noetic    robostack
ros-noetic-actionlib      1.13.2          py39h0e84094_11    robostack
ros-noetic-actionlib-msgs 1.13.1          py39h6c31a18_11    robostack
ros-noetic-actionlib-tutorials 0.2.0           py39h6c31a18_11    robostack
ros-noetic-angles         1.9.13          py39h6c31a18_11    robostack
ros-noetic-bond           1.8.6           py39h6c31a18_11    robostack
ros-noetic-bond-core      1.8.6           py39h6c31a18_11    robostack
ros-noetic-bondcpp        1.8.6           py39h0e84094_11    robostack
ros-noetic-bondpy         1.8.6           py39h6c31a18_11    robostack
ros-noetic-catkin         0.8.10          py39h6c31a18_12    robostack
ros-noetic-class-loader   0.5.0           py39hf195022_11    robostack
ros-noetic-cmake-modules  0.5.0           py39h6c31a18_11    robostack
ros-noetic-common-msgs    1.13.1          py39h6c31a18_11    robostack
ros-noetic-common-tutorials 0.2.0           py39h6c31a18_11    robostack
ros-noetic-control-msgs   1.5.2           py39h6c31a18_11    robostack
ros-noetic-cpp-common     0.7.2           py39ha49af28_11    robostack
ros-noetic-cv-bridge      1.16.0          py39h69ad0ca_11    robostack
ros-noetic-desktop        1.5.0           py39h6c31a18_11    robostack
ros-noetic-diagnostic-aggregator 1.11.0          py39h6c31a18_11    robostack
ros-noetic-diagnostic-analysis 1.11.0          py39h6c31a18_11    robostack
ros-noetic-diagnostic-common-diagnostics 1.11.0          py39h6c31a18_11    robostack
ros-noetic-diagnostic-msgs 1.13.1          py39h6c31a18_11    robostack
ros-noetic-diagnostic-updater 1.11.0          py39h6c31a18_11    robostack
ros-noetic-diagnostics    1.11.0          py39h6c31a18_11    robostack
ros-noetic-dynamic-reconfigure 1.7.2           py39h0e84094_12    robostack
ros-noetic-eigen-conversions 1.13.2          py39h6c31a18_11    robostack
ros-noetic-executive-smach 2.5.0           py39h6c31a18_11    robostack
ros-noetic-filters        1.9.1           py39h0e84094_11    robostack
ros-noetic-gencpp         0.6.5           py39h6c31a18_11    robostack
ros-noetic-geneus         3.0.0           py39h6c31a18_11    robostack
ros-noetic-genlisp        0.4.18          py39h6c31a18_11    robostack
ros-noetic-genmsg         0.5.16          py39h6c31a18_11    robostack
ros-noetic-gennodejs      2.0.2           py39h6c31a18_11    robostack
ros-noetic-genpy          0.6.15          py39h3173b27_11    robostack
ros-noetic-geometry       1.13.2          py39h6c31a18_11    robostack
ros-noetic-geometry-msgs  1.13.1          py39h6c31a18_11    robostack
ros-noetic-geometry-tutorials 0.2.3           py39h6c31a18_11    robostack
ros-noetic-gl-dependency  1.1.2           py39h6c31a18_11    robostack
ros-noetic-image-transport 1.12.0          py39h6c31a18_11    robostack
ros-noetic-interactive-marker-tutorials 0.11.0          py39h6c31a18_11    robostack
ros-noetic-interactive-markers 1.12.0          py39h6c31a18_11    robostack
ros-noetic-joint-state-publisher 1.15.0          py39h6c31a18_11    robostack
ros-noetic-joint-state-publisher-gui 1.15.0          py39h6c31a18_11    robostack
ros-noetic-kdl-conversions 1.13.2          py39h6c31a18_11    robostack
ros-noetic-kdl-parser     1.14.1          py39h3d7be1e_11    robostack
ros-noetic-laser-geometry 1.6.7           py39ha9297cf_11    robostack
ros-noetic-librviz-tutorial 0.11.0          py39h6c31a18_11    robostack
ros-noetic-map-msgs       1.14.1          py39h6c31a18_11    robostack
ros-noetic-media-export   0.3.0           py39h6c31a18_11    robostack
ros-noetic-message-filters 1.15.14         py39h0e84094_11    robostack
ros-noetic-message-generation 0.4.1           py39h6c31a18_11    robostack
ros-noetic-message-runtime 0.4.13          py39h6c31a18_11    robostack
ros-noetic-mk             1.15.8          py39h6c31a18_11    robostack
ros-noetic-nav-msgs       1.13.1          py39h6c31a18_11    robostack
ros-noetic-nodelet        1.10.2          py39ha9297cf_11    robostack
ros-noetic-nodelet-core   1.10.2          py39h6c31a18_11    robostack
ros-noetic-nodelet-topic-tools 1.10.2          py39ha9297cf_11    robostack
ros-noetic-nodelet-tutorial-math 0.2.0           py39h6c31a18_11    robostack
ros-noetic-pcl-conversions 1.7.4           py39h22dc883_12    robostack
ros-noetic-pcl-msgs       0.3.0           py39h6c31a18_11    robostack
ros-noetic-pcl-ros        1.7.4           py39h22dc883_12    robostack
ros-noetic-perception-pcl 1.7.4           py39h6c31a18_12    robostack
ros-noetic-pluginlib      1.13.0          py39ha92c76b_11    robostack
ros-noetic-pluginlib-tutorials 0.2.0           py39h6c31a18_11    robostack
ros-noetic-python-qt-binding 0.4.4           py39h6c31a18_11    robostack
ros-noetic-qt-dotgraph    0.4.2           py39h6c31a18_11    robostack
ros-noetic-qt-gui         0.4.2           py39h6c31a18_11    robostack
ros-noetic-qt-gui-cpp     0.4.2           py39h6c31a18_11    robostack
ros-noetic-qt-gui-py-common 0.4.2           py39h6c31a18_11    robostack
ros-noetic-qwt-dependency 1.1.1           py39h6c31a18_11    robostack
ros-noetic-resource-retriever 1.12.7          py39he0e12a9_11    robostack
ros-noetic-robot          1.5.0           py39h6c31a18_11    robostack
ros-noetic-robot-state-publisher 1.15.2          py39h6c31a18_11    robostack
ros-noetic-ros            1.15.8          py39h6c31a18_11    robostack
ros-noetic-ros-base       1.5.0           py39h6c31a18_11    robostack
ros-noetic-ros-comm       1.15.14         py39h6c31a18_11    robostack
ros-noetic-ros-core       1.5.0           py39h6c31a18_11    robostack
ros-noetic-ros-environment 1.3.2           py39h6c31a18_11    robostack
ros-noetic-ros-tutorials  0.10.2          py39h6c31a18_11    robostack
ros-noetic-rosbag         1.15.14         py39h0e84094_11    robostack
ros-noetic-rosbag-migration-rule 1.0.1           py39h6c31a18_11    robostack
ros-noetic-rosbag-storage 1.15.14         py39hc20ae3e_11    robostack
ros-noetic-rosbash        1.15.8          py39h6c31a18_11    robostack
ros-noetic-rosboost-cfg   1.15.8          py39h6c31a18_11    robostack
ros-noetic-rosbuild       1.15.8          py39h6c31a18_11    robostack
ros-noetic-rosclean       1.15.8          py39h6c31a18_11    robostack
ros-noetic-rosconsole     1.14.3          py39h3a4b664_11    robostack
ros-noetic-rosconsole-bridge 0.5.4           py39h4396f1a_11    robostack
ros-noetic-roscpp         1.15.14         py39h0e84094_11    robostack
ros-noetic-roscpp-core    0.7.2           py39h6c31a18_11    robostack
ros-noetic-roscpp-serialization 0.7.2           py39h6c31a18_11    robostack
ros-noetic-roscpp-traits  0.7.2           py39h6c31a18_11    robostack
ros-noetic-roscpp-tutorials 0.10.2          py39h0e84094_11    robostack
ros-noetic-roscreate      1.15.8          py39h6c31a18_11    robostack
ros-noetic-rosgraph       1.15.14         py39h6c31a18_11    robostack
ros-noetic-rosgraph-msgs  1.11.3          py39h6c31a18_11    robostack
ros-noetic-roslang        1.15.8          py39h6c31a18_11    robostack
ros-noetic-roslaunch      1.15.14         py39h6c31a18_11    robostack
ros-noetic-roslib         1.15.8          py39h0e84094_11    robostack
ros-noetic-roslint        0.12.0          py39h6c31a18_11    robostack
ros-noetic-roslisp        1.9.24          py39h6c31a18_11    robostack
ros-noetic-roslz4         1.15.14         py39h6c31a18_11    robostack
ros-noetic-rosmake        1.15.8          py39h6c31a18_11    robostack
ros-noetic-rosmaster      1.15.14         py39h6c31a18_11    robostack
ros-noetic-rosmsg         1.15.14         py39h6c31a18_11    robostack
ros-noetic-rosnode        1.15.14         py39h6c31a18_11    robostack
ros-noetic-rosout         1.15.14         py39h6c31a18_11    robostack
ros-noetic-rospack        2.6.2           py39ha92c76b_11    robostack
ros-noetic-rosparam       1.15.14         py39h6c31a18_11    robostack
ros-noetic-rospy          1.15.14         py39h6c31a18_11    robostack
ros-noetic-rospy-tutorials 0.10.2          py39h6c31a18_11    robostack
ros-noetic-rosservice     1.15.14         py39h6c31a18_11    robostack
ros-noetic-rostest        1.15.14         py39h0e84094_11    robostack
ros-noetic-rostime        0.7.2           py39h0e84094_11    robostack
ros-noetic-rostopic       1.15.14         py39h6c31a18_11    robostack
ros-noetic-rosunit        1.15.8          py39h6c31a18_11    robostack
ros-noetic-roswtf         1.15.14         py39h6c31a18_11    robostack
ros-noetic-rqt-action     0.4.9           py39h6c31a18_11    robostack
ros-noetic-rqt-bag        0.5.1           py39h6c31a18_11    robostack
ros-noetic-rqt-bag-plugins 0.5.1           py39h6c31a18_11    robostack
ros-noetic-rqt-common-plugins 0.4.9           py39h6c31a18_11    robostack
ros-noetic-rqt-console    0.4.11          py39h6c31a18_11    robostack
ros-noetic-rqt-dep        0.4.12          py39h6c31a18_11    robostack
ros-noetic-rqt-graph      0.4.14          py39h6c31a18_11    robostack
ros-noetic-rqt-gui        0.5.3           py39h6c31a18_12    robostack
ros-noetic-rqt-gui-cpp    0.5.2           py39h6c31a18_11    robostack
ros-noetic-rqt-gui-py     0.5.3           py39h6c31a18_12    robostack
ros-noetic-rqt-image-view 0.4.16          py39h6c31a18_11    robostack
ros-noetic-rqt-launch     0.4.9           py39h6c31a18_11    robostack
ros-noetic-rqt-logger-level 0.4.11          py39h6c31a18_11    robostack
ros-noetic-rqt-moveit     0.5.10          py39h6c31a18_11    robostack
ros-noetic-rqt-msg        0.4.10          py39h6c31a18_11    robostack
ros-noetic-rqt-nav-view   0.5.7           py39h6c31a18_11    robostack
ros-noetic-rqt-plot       0.4.13          py39h6c31a18_11    robostack
ros-noetic-rqt-pose-view  0.5.11          py39h6c31a18_11    robostack
ros-noetic-rqt-publisher  0.4.10          py39h6c31a18_11    robostack
ros-noetic-rqt-py-common  0.5.2           py39h6c31a18_11    robostack
ros-noetic-rqt-py-console 0.4.10          py39h6c31a18_11    robostack
ros-noetic-rqt-reconfigure 0.5.4           py39h6c31a18_11    robostack
ros-noetic-rqt-robot-dashboard 0.5.8           py39h6c31a18_11    robostack
ros-noetic-rqt-robot-monitor 0.5.13          py39h6c31a18_11    robostack
ros-noetic-rqt-robot-plugins 0.5.8           py39h6c31a18_11    robostack
ros-noetic-rqt-robot-steering 0.5.12          py39h6c31a18_11    robostack
ros-noetic-rqt-runtime-monitor 0.5.9           py39h6c31a18_11    robostack
ros-noetic-rqt-rviz       0.7.0           py39ha9297cf_11    robostack
ros-noetic-rqt-service-caller 0.4.10          py39h6c31a18_11    robostack
ros-noetic-rqt-shell      0.4.11          py39h6c31a18_11    robostack
ros-noetic-rqt-srv        0.4.9           py39h6c31a18_11    robostack
ros-noetic-rqt-tf-tree    0.6.2           py39h6c31a18_11    robostack
ros-noetic-rqt-top        0.4.10          py39h6c31a18_11    robostack
ros-noetic-rqt-topic      0.4.13          py39h6c31a18_11    robostack
ros-noetic-rqt-web        0.4.10          py39h6c31a18_11    robostack
ros-noetic-rviz           1.14.13         py39hb659aec_11    robostack
ros-noetic-rviz-plugin-tutorials 0.11.0          py39h6c31a18_11    robostack
ros-noetic-rviz-python-tutorial 0.11.0          py39h6c31a18_11    robostack
ros-noetic-self-test      1.11.0          py39h6c31a18_11    robostack
ros-noetic-sensor-msgs    1.13.1          py39h6c31a18_11    robostack
ros-noetic-shape-msgs     1.13.1          py39h6c31a18_11    robostack
ros-noetic-smach          2.5.0           py39h6c31a18_11    robostack
ros-noetic-smach-msgs     2.5.0           py39h6c31a18_11    robostack
ros-noetic-smach-ros      2.5.0           py39h6c31a18_11    robostack
ros-noetic-smclib         1.8.6           py39h6c31a18_11    robostack
ros-noetic-std-msgs       0.5.13          py39h6c31a18_11    robostack
ros-noetic-std-srvs       1.11.3          py39h6c31a18_11    robostack
ros-noetic-stereo-msgs    1.13.1          py39h6c31a18_11    robostack
ros-noetic-tf             1.13.2          py39ha2f7687_11    robostack
ros-noetic-tf-conversions 1.13.2          py39h6c31a18_11    robostack
ros-noetic-tf2            0.7.5           py39h4396f1a_11    robostack
ros-noetic-tf2-eigen      0.7.5           py39h6c31a18_11    robostack
ros-noetic-tf2-geometry-msgs 0.7.5           py39h6c31a18_11    robostack
ros-noetic-tf2-kdl        0.7.5           py39h6c31a18_11    robostack
ros-noetic-tf2-msgs       0.7.5           py39h6c31a18_11    robostack
ros-noetic-tf2-py         0.7.5           py39h6c31a18_11    robostack
ros-noetic-tf2-ros        0.7.5           py39h6c31a18_11    robostack
ros-noetic-topic-tools    1.15.14         py39h6c31a18_11    robostack
ros-noetic-trajectory-msgs 1.13.1          py39h6c31a18_11    robostack
ros-noetic-turtle-actionlib 0.2.0           py39h6c31a18_11    robostack
ros-noetic-turtle-tf      0.2.3           py39h6c31a18_11    robostack
ros-noetic-turtle-tf2     0.2.3           py39h6c31a18_11    robostack
ros-noetic-turtlesim      0.10.2          py39h0e84094_11    robostack
ros-noetic-urdf           1.13.2          py39h3d7be1e_11    robostack
ros-noetic-urdf-parser-plugin 1.13.2          py39h6c31a18_11    robostack
ros-noetic-urdf-tutorial  0.5.0           py39h6c31a18_11    robostack
ros-noetic-visualization-marker-tutorials 0.11.0          py39h6c31a18_11    robostack
ros-noetic-visualization-msgs 1.13.1          py39h6c31a18_11    robostack
ros-noetic-visualization-tutorials 0.11.0          py39h6c31a18_11    robostack
ros-noetic-viz            1.5.0           py39h6c31a18_11    robostack
ros-noetic-webkit-dependency 1.1.2           py39h6c31a18_11    robostack
ros-noetic-xacro          1.14.11         py39h6c31a18_11    robostack
ros-noetic-xmlrpcpp       1.15.14         py39h0e84094_11    robostack
rosdep                    0.21.0             pyhd8ed1ab_1    conda-forge
rosdistro                 0.8.3            py39hcbf5309_3    conda-forge
rospkg                    1.4.0              pyhd8ed1ab_0    conda-forge
sdl2                      2.0.22               h0e60522_0    conda-forge
setuptools                62.1.0           py39hcbf5309_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.38.5               h8ffe710_0    conda-forge
tbb                       2021.5.0             h2d74725_1    conda-forge
tbb-devel                 2021.5.0             h2d74725_1    conda-forge
tinyxml                   2.6.2                h2d74725_2    conda-forge
tinyxml2                  9.0.0                h0e60522_2    conda-forge
tk                        8.6.12               h8ffe710_0    conda-forge
tzdata                    2022a                h191b570_0    conda-forge
ucrt                      10.0.20348.0         h57928b3_0    conda-forge
unicodedata2              14.0.0           py39hb82d6ee_1    conda-forge
urdfdom                   2.3.5                h2d74725_0    conda-forge
urdfdom_headers           1.0.6                h5362a0b_2    conda-forge
utfcpp                    3.2.1                haa95532_0    anaconda
vc                        14.2                 hb210afc_6    conda-forge
vs2015_runtime            14.29.30037          h902a5da_6    conda-forge
vs2017_win-64             19.16.27032.1        hb4161e2_3    anaconda
vs2019_win-64             19.27.29111          ha89c4d3_2    anaconda
vswhere                   2.8.4                haa95532_0    anaconda
vtk                       9.1.0           qt_py39h1ab545e_207    conda-forge
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
win32_setctime            1.1.0              pyhd3eb1b0_0    anaconda
xorg-kbproto              1.0.7             hcd874cb_1002    conda-forge
xorg-libice               1.0.10               hcd874cb_0    conda-forge
xorg-libsm                1.2.3             hcd874cb_1000    conda-forge
xorg-libx11               1.7.2                hcd874cb_0    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xorg-libxext              1.3.4                hcd874cb_1    conda-forge
xorg-libxpm               3.5.13               hcd874cb_0    conda-forge
xorg-libxt                1.2.1                hcd874cb_2    conda-forge
xorg-xextproto            7.3.0             hcd874cb_1002    conda-forge
xorg-xproto               7.0.31            hcd874cb_1007    conda-forge
xz                        5.2.5                h62dcd97_1    conda-forge
yaml                      0.2.5                h8ffe710_2    conda-forge
yaml-cpp                  0.6.3                ha925a31_4    conda-forge
zlib                      1.2.11            h8ffe710_1014    conda-forge
zstd                      1.5.2                h6255e5f_0    conda-forge
zziplib                   0.13.69              h1d00b33_1    conda-forge

**Comment by vanem** [comment]
I now realize, are the packages suppose to be a mix of robostack and conda-forge channels like this?

**Comment by traversaro** [comment]
> I now realize, are the packages suppose to be a mix of robostack and conda-forge channels like this?

Yes, that is totally ok. `conda-forge` is the basis on which `robostack` is built. What is more dangerous is mixing `anaconda` and `conda-forge`, as it seems that it is happening in your environment.

Which commands did you used to build your environment? Ideally it should contain only `conda-forge` and `robostack` packages, not `anaconda` one.

**Comment by traversaro** [comment]
I am definitely not an expert, but I guess the problem may be the `.condarc` in user home?

**Comment by vanem** [comment]
@traversaro thanks! I cleaned .condarc from user homedir and reinstalled, and that solved the problem

**Comment by kneave** [comment]
To add another cause of this for those that find themselves here, it's worth checking if `/etc/ros/rosdep/sources.list.d/20-default.list` exists. I must have run `sudo rosdep init` at some point which was the cause of the `Bad installer` error in my case.
