### ISSUE TITLE
Installation steps for ROS2 Foxy

### ISSUE THREAD

**Issue by mortenterhart** [RoboStack/ros-noetic#268]
I want to install and run ROS2 Foxy in a `conda` environment to manage dependencies and not to clutter my global environment with ROS packages. However, I can't find installation instructions for Foxy as the corresponding [`RoboStack/ros-foxy`](https://github.com/RoboStack/ros-foxy) repository has an empty readme file. Also there is no equivalent `ros-foxy-desktop` available as there is for ROS2 Noetic for example.

How can I install ROS2 Foxy in a `conda` environment on Linux x64?
Any help would be appreciated.

**Comment by traversaro** [comment]
Hi @mortenterhart ! The ROS2 conda packages are a work in progress, and the initial work was done for the galactic distro, while no conda packages are available for foxy. https://github.com/RoboStack/ros-foxy was just a repo used for initial experiments that then moved to target galactic.

**Comment by Tobias-Fischer** [comment]
We actually did build some foxy packages (including ros-core) but never desktop. Hopefully galactic is an option for you :)
