### ISSUE TITLE
visual studio 2022 support?

### ISSUE THREAD

**Issue by zhengzh** [RoboStack/ros-noetic#278]

**Comment by traversaro** [comment]
Hi @zhengzh, could you elaborate a bit more your question? At the moment there is no `vs2022_win-64` package in conda-forge (see https://github.com/conda-forge/vc-feedstock/pull/46). However, if you are building a simple CMake project a possible workaround is to use the `Visual Studio 17 2022` CMake generator, for example:
~~~
cd simplecmakeprojectdir
mkdir build
cd build
cmake -G"Visual Studio 17 2022" ..
cmake --build . --config Release 
~~~

**Comment by zhengzh** [comment]
Thanks! I already installed `Visual Studio 17 2022`, And if i want to try `ROS` on `Windows`,  now I have to install `Visual Studio 16 2017`
