### ISSUE TITLE
Build convex-decomposition

### ISSUE THREAD

**Issue by JKBehrens** [RoboStack/ros-noetic#287]
Hi @Tobias-Fischer,

After setting up a new environment with ros noetic as described in the getting started page (https://robostack.github.io/GettingStarted.html), I can not install many packages. For example,

```mamba install ros-noetic-convex-decomposition```

fails with 

```
mamba install ros-noetic-convex-decomposition

                  __    __    __    __
                 /  \  /  \  /  \  /  \
                /    \/    \/    \/    \
███████████████/  /██/  /██/  /██/  /████████████████████████
              /  / \   / \   / \   / \  \____
             /  /   \_/   \_/   \_/   \    o \__,
            / _/                       \_____/  `
            |/
        ███╗   ███╗ █████╗ ███╗   ███╗██████╗  █████╗
        ████╗ ████║██╔══██╗████╗ ████║██╔══██╗██╔══██╗
        ██╔████╔██║███████║██╔████╔██║██████╔╝███████║
        ██║╚██╔╝██║██╔══██║██║╚██╔╝██║██╔══██╗██╔══██║
        ██║ ╚═╝ ██║██║  ██║██║ ╚═╝ ██║██████╔╝██║  ██║
        ╚═╝     ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝╚═════╝ ╚═╝  ╚═╝

        mamba (0.19.1) supported by @QuantStack

        GitHub:  https://github.com/mamba-org/mamba
        Twitter: https://twitter.com/QuantStack

█████████████████████████████████████████████████████████████


Looking for: ['ros-noetic-convex-decomposition']

conda-forge/linux-64     Using cache
conda-forge/noarch       Using cache
pkgs/main/linux-64       [====================] (00m:00s) No change
pkgs/r/linux-64          [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
robostack-experimental/l [====================] (00m:00s) No change
robostack/noarch         [====================] (00m:00s) No change
robostack/linux-64       [====================] (00m:00s) No change
robostack-experimental/n [====================] (00m:00s) No change

Pinned packages:
  - python 3.9.*


Encountered problems while solving:
  - package ros-noetic-convex-decomposition-0.1.12-py38he9ab703_9 requires python, but none of the providers can be installed
```

This problem also occurred for packages that I installed. In these cases, I could often install them one by one. But as soon as the dependency on `python` appears, there is no chance. 

Thank you for your help in advance!
Jan

[debug_env.yml.txt](https://github.com/RoboStack/ros-noetic/files/9646299/debug_env.yml.txt)

**Comment by Tobias-Fischer** [comment]
Same issue as in https://github.com/RoboStack/ros-noetic/issues/262 - the `convex-decomposition` package has not been built for python 3.9. Please open a pull request adding it to the vinca_*.yaml files and we will build it in our CI.

**Comment by v4hn** [comment]
@Tobias-Fischer you built various packages for 3.8 before and I would not expect any issue with compiling things like convex-decomposition, ivcon, rosrt, gazebo-ros, et al. in the 3.9 environment (in fact it works well by hand).
But [you disabled them 8 months ago](https://github.com/RoboStack/ros-noetic/commit/5ae5d075358cf2f4cbc7c11dbed81c6c0efecf52) to "reduce maintainer burden".
Did you need to cut down CI runs? Would it be a big burden to uncomment all of them again?
It is really annoying to get this error message every time you try to install a package robostack knows and I would only expect to see it if CI actually tried to build the new package *and failed*.
If something fails to compile you could still comment it out in the configs (or create an issue and ignore the failed runs).

**Comment by Tobias-Fischer** [comment]
Hi @v4hn, I agree it is an annoying issue. However, it is very easy for anyone to open a pull request and add the packages that are wanted again. In the py38 builds I tried to build as many packages as possible to see how it goes and how much time it would take, and unfortunately realised it would take too much time to do regularly for the current maintainer team.

Re maintainer burden: For many of the packages we created patches to build them here, and over time because of upstream changes they don’t apply cleanly anymore. If someone has capacity to either update the patches or reduce the full list of packages to packages that build without issues in CI, this would be highly appreciated. At the moment unfortunately I don’t have this capacity anymore, but this is an open source project so anyone can get involved very easily. I’m happy to answer any questions that come up in the process. There is also an issue open here to upstream our patches, this would help a lot, too.

**Comment by v4hn** [comment]
I've done similar work w.r.t. patch management and fixes in Linux rolling release for the last 15 years, so I absolutely understand your reasoning and sympathize. For the whole of ROS one this is clearly a fulfilling full-time job. :)

Still, it would help a lot if you could consider a workflow that:
1. keeps everything active in the pipeline that you spent work on before and that ran successfully
2. shows a summary page that shows whether each package built successfully, failed to build (that's roughly what https://robostack.github.io/noetic.html is, but with the packages disabled it never turns red!)
3. and you can click on failures to see error messages of the build process (not supported on your website and the only way to see the errors, that I can see right away, is to setup the environment required and try to compile locally

Would you merge a PR that enables all your commented out packages again to see what works/fails?

**Comment by Tobias-Fischer** [comment]
Those are great suggestions! If you open a PR it will build packages within the PR on the GitHub CI, so this addresses your third point. So yes please, if you open a PR we could see where we stand :).
An alternative, faster way might be to build locally with the boa flag —continue-on-failure and then do a diff between the packages listed in the vinca.yaml and the packages that were actually build.
If you want to get involved and have better access to play around I’d also be happy to make you a maintainer if you are interested (after checking that other maintainers are okay with that).

**Comment by v4hn** [comment]
I created a PR to have CI load spike for a bit. :)

Thanks for the offer @Tobias-Fischer, I know everyone is short on volunteer maintainers. I have my hand full with various other obligations, including [ROS-O](https://github.com/ros-o) which collaborates with RoboStack in patches. :-)

**Comment by Tobias-Fischer** [comment]
Now available in the robostack-staging channel.
