### ISSUE TITLE
Unable to Install move_base package

### ISSUE THREAD

**Issue by GaganBhat** [RoboStack/ros-noetic#307]
I am trying to install the move_base package inside of my robostack env with the command `mamba install ros-noetic-move-base`. 

According to the [documentation](https://robostack.github.io/noetic.html), this package should be available.

I see the following error:

```
Looking for: ['ros-noetic-move-base']

conda-forge/osx-arm64                                4.3MB @   1.8MB/s  2.5s
conda-forge/noarch                                  10.4MB @   3.1MB/s  3.7s

Pinned packages:
  - python 3.9.*


Encountered problems while solving:
  - nothing provides requested ros-noetic-move-base
```

Any ideas what I might be doing wrong?

Alternatively, if I have to use Python 3.8 for this, how can I set up robostack with that older python? The same command provided in the README does not work.

Thanks!

System:
M1 Max MBP
Python 3.9
Mambaforge based installation

**Comment by Tobias-Fischer** [comment]
Now available in the `robostack-staging` channel
