### ISSUE TITLE
ros-noetic-moveit CONFLICTS with ros-noetic-desktop-full (MacOS 12.6 M1 + Linux ARM64)

### ISSUE THREAD

**Issue by kaimietis52** [RoboStack/ros-noetic#314]
I have tried many times to install moveit on top of desktop-full installation and mamba always returns a conflict between these two packages:

```
Looking for: ['ros-noetic-moveit']

conda-forge/osx-arm64    Using cache
conda-forge/noarch       Using cache
robostack-humble/osx-arm [====================] (00m:00s) No change
robostack-humble/noarch  [====================] (00m:00s) No change
robostack-experimental/n [====================] (00m:00s) No change
robostack/osx-arm64      [====================] (00m:00s) No change
robostack/noarch         [====================] (00m:00s) No change
pkgs/main/osx-arm64      [====================] (00m:00s) No change
pkgs/main/noarch         [====================] (00m:00s) No change
pkgs/r/osx-arm64         [====================] (00m:00s) No change
pkgs/r/noarch            [====================] (00m:00s) No change
robostack-experimental/o [====================] (00m:00s) No change

Pinned packages:
  - python 3.9.*

Encountered problems while solving:
  - package libgdal-3.4.2-h3df7942_6 requires icu >=69.1,<70.0a0, but none of the providers can be installed
```

This happens on a clean conda environment after following these steps:
1. conda install mamba -c conda-forge
2. conda create -n ROS python=3.9
3. conda activate ROS
4. conda config --env --add channels conda-forge
    conda config --env --add channels robostack
    conda config --env --add channels robostack-experimental
5. mamba install ros-noetic-desktop-full
6. mamba install ros-noetic-moveit

I have come across this issue on mac running apple silicon, however I also tried setting up a virtual ubuntu arm64 environment following these steps and got the same exact error.

**Comment by Tobias-Fischer** [comment]
This has been resolved with the new packages in the robostack-staging channel.
