### ISSUE TITLE
Python 3.11 packages in user channel

### ISSUE THREAD

**Issue by lianghongzhuo** [RoboStack/ros-noetic#339]
Thank you for the great framework!
I have built ros linux64 in python3.11 and uploaded it to anaconda. https://anaconda.org/lianghongzhuo/repo
Do you interested in this? How can I contribute?

**Comment by Tobias-Fischer** [comment]
Awesome, thank you for this!

@wolfv - how should we deal with this?
@lianghongzhuo - a bit of background: so far we tried to limit locally built packages as much as possible, as there are no publicly available build logs etc. in this case. However, I agree that building locally is much easier and pain-free compared to our current CI solution ..

**Comment by lianghongzhuo** [comment]
By the way, is there a way to set up vinca to generate recipes from the upstream source code? Many patches I made for build python3.11 are just the diff with the upstream source code. If we can build a bleed edge binary then the workload of making patches are reduced.

**Comment by Tobias-Fischer** [comment]
Unfortunately not an easy one :(. @wolfv maybe you could point @lianghongzhuo to the right spot in vinca which would enable this?

@lianghongzhuo could you please open a pull request with the additional patches that you used? This would be awesome!

**Comment by lianghongzhuo** [comment]
sure, done.

**Comment by Tobias-Fischer** [comment]
We'll soon release Python 3.11 packages in #418
