### ISSUE TITLE
Package request: ros-noetic-pinocchio for python 3.9 in robostack-staging

### ISSUE THREAD

**Issue by VModugno** [RoboStack/ros-noetic#364]
### Package name

ros-noetic-pinocchio

### Operating System(s)

- [X] linux-64
- [ ] linux-aarch64
- [ ] osx-64
- [ ] osx-arm64
- [ ] win-64

### Additional context (optional)

Dear all,

it seems that ros-noetic-pinocchio is only available in robostack and not in robostack-staging. if I try to install ros-noetic-pinocchio with mamba in mambaforge using python 3.9 from the robostack channel It says that it does not exist (there is only the version for python 3.8)
thank you again for your help 

have a great weekend

Valerio

**Comment by traversaro** [comment]
Note that we have pinocchio package directly in conda-forge, did you tried to check if it works in your use case?

**Comment by Tobias-Fischer** [comment]
All done
