### ISSUE TITLE
Package request: microstrain-inertial-driver, microstrain-inertial-msgs

### ISSUE THREAD

**Issue by saeedarabi92** [RoboStack/ros-noetic#369]
### Package name

microstrain-inertial-driver, microstrain-inertial-msgs

### Operating System(s)

- [X] linux-64
- [X] linux-aarch64
- [X] osx-64
- [ ] osx-arm64
- [ ] win-64

### Additional context (optional)

Thank you for the great work!

**Comment by Tobias-Fischer** [comment]
Should be available in an hour.
