### ISSUE TITLE
CCD package not found while catkin making the workspace

### ISSUE THREAD

**Issue by CMA020** [RoboStack/ros-noetic#392]
I had conda installed ccd reactivated the env but still facing the same error . should I source something before i work with ros in a conda env?

**Comment by traversaro** [comment]
> I had conda installed ccd reactivated the env but still facing the same error . should I source something before i work with ros in a conda env?
> 

Can you provide the information required in the issue template (i.e. conda info and mamba list)? Thanks!

**Comment by Tobias-Fischer** [comment]
Closing as additional information is missing - please reopen once provided.
