### ISSUE TITLE
Try Mac ARM runner instance

### ISSUE THREAD

**Issue by Tobias-Fischer** [RoboStack/ros-noetic#428]
See https://github.blog/2023-10-02-introducing-the-new-apple-silicon-powered-m1-macos-larger-runner-for-github-actions/

I’m not quite sure whether it’s fully public yet or not.

**Comment by traversaro** [comment]
From what I understand, all minutes used by those runners are billed, even the one in public repos.

**Comment by Tobias-Fischer** [comment]
Yes, I figures this too :(. It might be worth looking again at self-hosted runners, or https://cirrus-ci.org
