### ISSUE TITLE
Package request: p2os

### ISSUE THREAD

**Issue by nixwebb** [RoboStack/ros-noetic#439]
### Package name

p2os

### Operating System(s)

- [X] linux-64
- [ ] linux-aarch64
- [ ] osx-64
- [ ] osx-arm64
- [ ] win-64

### Additional context (optional)

I'm investigating the use of RoboStack for continuing to work with my Pioneer mobile robot. There are a lot of packages that I currently use that aren't in RoboStack. I principally work with ROSARIA, having the Aria library on the robot, although p2os also works. There are additional libraries I use regularly, such as leg-detector, but I have no idea how easy it is for you to pull packages into the RoboStack environment. If ROSARIA or p2os is possible, I can provide a list of desirable packages, OR make individual package pull requests, which ever is easier. 

### Links and references (optional)

http://wiki.ros.org/p2os_driver

**Comment by Tobias-Fischer** [comment]
Will be included in #418
