### ISSUE TITLE
PYTHONPATH catkin patch

### ISSUE THREAD

**Issue by wolfv** [RoboStack/ros-noetic#45]
We currently comment out setting the PYTHONPATH which is fine / correct for the conda environment. However, the PYTHONPATH is also not appended for _new_ catkin workspaces, and then tools like rosrun apparently don't work fine. So we should have a bit better logic there.

Note: we can get the prefix from the python installation with `sys.prefix`

**Comment by Tobias-Fischer** [comment]
I'll reopen till we rebuild the package.
