### ISSUE TITLE
Package request: ros-noetic-lanelet2

### ISSUE THREAD

**Issue by mantkiew** [RoboStack/ros-noetic#467]
### Package name

ros-noetic-lanelet2

### Operating System(s)

- [X] linux-64
- [ ] linux-aarch64
- [ ] osx-64
- [ ] osx-arm64
- [ ] win-64

### Additional context (optional)

It is available only in ROS Galactic so far but an older version. The latest is 1.2.1, which contains things I need.

### Links and references (optional)

https://github.com/fzi-forschungszentrum-informatik/Lanelet2

**Comment by Tobias-Fischer** [comment]
All done
