### ISSUE TITLE
Package request: ros-humble-moveit-servo

### ISSUE THREAD

**Issue by MannavaVivek** [RoboStack/ros-noetic#473]
### Package name

ros-humble-moveit-servo

### Operating System(s)

- [ ] linux-64
- [ ] linux-aarch64
- [ ] osx-64
- [X] osx-arm64
- [X] win-64

### Additional context (optional)

Package is already available for linux variants and osx-64, but not for osx-arm64 and win-64

**Comment by Tobias-Fischer** [comment]
For win-64, we'd need libspnav, which cannot be built for Windows

**Comment by Tobias-Fischer** [comment]
Added for osx-arm64 in https://github.com/RoboStack/ros-noetic/pull/474
