### ISSUE TITLE
Package request: slam_gmapping

### ISSUE THREAD

**Issue by GokulEdakkePuram** [RoboStack/ros-noetic#478]
### Package name

slam_gmapping

### Operating System(s)

- [ ] linux-64
- [ ] linux-aarch64
- [X] osx-64
- [X] osx-arm64
- [ ] win-64

### Additional context (optional)

Package for OpenSlam's Gmapping. It provides laser-based SLAM and can create a 2-D occupancy grid map from laser and pose data.

### Links and references (optional)

ROS Documentation: http://wiki.ros.org/gmapping
GitHub Repo: https://github.com/ros-perception/slam_gmapping

**Comment by Tobias-Fischer** [comment]
Hi @GokulEdakkePuram  - if you create pull requests for the packages you are looking for, I’ll be able to merge - unfortunately I currently don’t have the capacity to action issues.

Best, Tobi

**Comment by Tobias-Fischer** [comment]
Fixed in #487
