### ISSUE TITLE
rosdep fails on Windows 10 

### ISSUE THREAD

**Issue by danzimmerman** [RoboStack/ros-noetic#49]
Seems identical to this: https://github.com/ros-infrastructure/rosdep/issues/610

Suggested fix works.

**Comment by traversaro** [comment]
Note that when using the RoboStack channel the logical equivalent of using rosdep is installing dependencies via conda-forge, see https://github.com/RoboStack/ros-noetic/issues/41 for a related issue.

**Comment by danzimmerman** [comment]
> Note that when using the RoboStack channel the logical equivalent of using rosdep is installing dependencies via conda-forge, see #41 for a related issue.

Right, and I guess generally conda will ensure that anything installed will come with its system dependencies, so something like `rosdep check` is redundant...

**Comment by Tobias-Fischer** [comment]
I suggest to continue discussion in https://github.com/RoboStack/ros-noetic/issues/41 and will close here.
