### ISSUE TITLE
JupyterLab-ros not for OSX-arm64

### ISSUE THREAD

**Issue by pebe-espana** [RoboStack/ros-noetic#490]
Hi,
I hope I am asking for this in the right place.
Tried in vain to install jupyterlab-ros on OSX-arm64 system(i.e. new M2 processor). Installation using 

"mamba install jupyterlab-ros -c robostack" will not install due to missing ros-noetic-tf2-web-republisher.

Trying to install

"conda install -c robostack ros-noetic-tf2-web-republisher"

separately also fails, as in anaconda.org the OSX-arm64 version is not available yet.
Any hope to have that supplied?
Thanks,
Peter

**Comment by Tobias-Fischer** [comment]
Have added tf2-web-republisher on all platforms now (on the robostack-staging channel), and let's use https://github.com/RoboStack/jupyter-ros/issues/167 for any remaining problems.
