### ISSUE TITLE
mavros package for Windows 10

### ISSUE THREAD

**Issue by Y-Grigoriy** [RoboStack/ros-noetic#53]
Hello, is it planning to add mavros package compatible with Windows? If yes, when can it be possible?

**Comment by Tobias-Fischer** [comment]
Do you want it to give a go and open a pull request? In this way you can assist us and accelerate getting the package built.

**Comment by Y-Grigoriy** [comment]
Unfortunately, I don't have enough skills to help in the package built. I just start to work with ROS for project aimed to development UAV. I plan to create new code based on the old version written by my colleague in Ubuntu using mavros.

**Comment by Tobias-Fischer** [comment]
Hi @Y-Grigoriy, I patched the mavros package to compile on Windows: https://github.com/RoboStack/ros-noetic/pull/57
I will merge this pull request soon. However, this is totally untested, and I will not have time to fix the package in the very likely case that things don't work. Feel free to test the package, and to open pull requests with changes if they are needed - it is easy to do so, and https://github.com/RoboStack/ros-noetic/blob/master/CONTRIBUTING.md describes how to do it.
